openapi: 3.0.0
info:
  title: Shopionz
  version: 1.0.0
servers:
  - url: https://project-ii-server.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: Auth
  - name: Menu
  - name: Categories
  - name: Product
  - name: Users
  - name: Shipping Method
  - name: Payment Method
  - name: Addresses
paths:
  /login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                usernameEmail: KostsPlayer
                password: 1qazxsw2
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /assign-role:
    post:
      tags:
        - Auth
      summary: Assign-Role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userId: 45
                role: Seller
      security:
        - noauthAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /registration:
    post:
      tags:
        - Auth
      summary: Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: test1
                email: test2@gmail.com
                password: 1qazxsw2
      security:
        - noauthAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /menu:
    get:
      tags:
        - Menu
      summary: Get-Menu
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /get-menu/{menuId}:
    get:
      tags:
        - Menu
      summary: Get-Menu:ID
      parameters:
        - name: menuId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /insert-menu:
    post:
      tags:
        - Menu
      summary: Create-Menu
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: test
                icon: test
                url: test
                is_active: 1
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /update-menu/{menuId}:
    put:
      tags:
        - Menu
      summary: Update-Menu
      parameters:
        - name: menuId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: test1
                icon: test2
                url: test3
                is_active: 0
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /delete-menu/{menuId}:
    delete:
      tags:
        - Menu
      summary: Delete-Menu
      parameters:
        - name: menuId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /category:
    get:
      tags:
        - Categories
      summary: Get-Categories
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /get-category/{categoryId}:
    get:
      tags:
        - Categories
      summary: Get-Category:ID
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /insert-category:
    post:
      tags:
        - Categories
      summary: Insert-Category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Idk
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /update-category/{categoryId}:
    put:
      tags:
        - Categories
      summary: Update-Category
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Idk1234
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /delete-category/{categoryId}:
    delete:
      tags:
        - Categories
      summary: Delete-Category
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /product:
    get:
      tags:
        - Product
      summary: Get-Product
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /get-product/{productId}:
    get:
      tags:
        - Product
      summary: Get-Product:ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /product-seller/{sellerId}:
    get:
      tags:
        - Product
      summary: Get-Seller:ID (User)
      parameters:
        - name: sellerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /delete-product/{productId}:
    delete:
      tags:
        - Product
      summary: Delete-Product
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /profiles:
    get:
      tags:
        - Users
      summary: Get-Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /profile/{userId}:
    get:
      tags:
        - Users
      summary: Get-User:ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /update-profile/{userId}:
    put:
      tags:
        - Users
      summary: Update-Profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: test2@gmail.com
                name: test1
                phone_number: "082133466199"
                password: $2b$10$ggm824EVH18UTKXQiMBjM.yyW34tMi..fuUx0IBVzObsJo/uoPr02
                image: 2.jpg
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /get-shipping:
    get:
      tags:
        - Shipping Method
      summary: Get-Shipping
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /get-payment:
    get:
      tags:
        - Payment Method
      summary: Get-Payment
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /provincies:
    get:
      tags:
        - Addresses
      summary: Provincies
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /regencies/{provinceId}:
    get:
      tags:
        - Addresses
      summary: Regencies
      parameters:
        - name: provinceId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /districts/{regencyId}:
    get:
      tags:
        - Addresses
      summary: Districts
      parameters:
        - name: regencyId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /villages/{districtId}:
    get:
      tags:
        - Addresses
      summary: Villages
      parameters:
        - name: districtId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /address/{userId}:
    get:
      tags:
        - Addresses
      summary: Get-Address:ID (User)
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /insert-address:
    post:
      tags:
        - Addresses
      summary: Insert-Address
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                provincies: 35
                regencies: 3508
                districts: 3508130
                villages: 3508130003
                address: Jalan Sarimanah 2
                userId: 2
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /main-address/{addressId}:
    put:
      tags:
        - Addresses
      summary: Main-Address:ID
      parameters:
        - name: addressId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: true
                userId: 2
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /delete-address/{addressId}:
    delete:
      tags:
        - Addresses
      summary: Delete-Address
      parameters:
        - name: addressId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
